class stack{
    constructor(layer,x,y,type){
        this.layer=layer
        this.position={x:x,y:y}
        this.type=type
        this.fade=0
        this.remove=false
        this.cancel=false
        this.stackers=[]
        this.click=false
        for(g=0,lg=current.combatants.length;g<lg;g++){
            this.stackers.push(round(current.combatants[g].stacking*100)/100)
        }
    }
    display(){
        this.layer.stroke(0,this.fade)
        this.layer.strokeWeight(2)
        if(this.type<4){
            this.layer.fill(100,125,150,this.fade)
        }
        else{
            this.layer.fill(150,100,100,this.fade)
        }
        this.layer.rect(this.position.x+6,this.position.y+6,36,30)
        this.layer.noStroke()
        this.layer.textSize(20)
        this.layer.fill(0,this.fade)
        if(this.type<4){
            this.layer.text(4-this.type,this.position.x+6,this.position.y+8)
        }
        else{
            this.layer.text(this.type-3,this.position.x+6,this.position.y+8)
        }
    }
    update(index,combatants){
        if(combatants[this.type].life<=0||this.cancel){
            this.fade-=1/15
        }
        else if(this.fade<1){
            this.fade+=1/15
        }
        if(this.position.x>=index*48+24){
            this.position.x-=3
        }
        if(this.fade<=0){
            this.remove=true
            current.stacking.use=false
        }
    }
}