types={
    combatant:[
        {name:'',alt:'',life:0,speed:0,damage:0,attacks:[],height:0,reward:0,pattern:0},//0
        {name:'Bill',alt:'',life:28,speed:11,damage:1,attacks:[1,27/*,29*/],height:75,reward:0,pattern:0},
        {name:'Tom',alt:'',life:36,speed:15,damage:1,attacks:[2,30/*,32*/],height:75,reward:0,pattern:0},
        {name:'Jon',alt:'',life:24,speed:9,damage:1,attacks:[24,33/*,35*/],height:75,reward:0,pattern:0},
        {name:'Eddy',alt:'',life:26,speed:12,damage:1,attacks:[25,36,37/*,38*/],height:72,reward:0,pattern:0},
        {name:'Lalex',alt:'',life:32,speed:14,damage:1,attacks:[1,40,41/*,42*/],height:78,reward:0,pattern:0},
        {name:'Scott',alt:'',life:30,speed:8,damage:1,attacks:[2,43/*,45*/],height:75,reward:0,pattern:0},
        {name:'Ollie',alt:'',life:28,speed:13,damage:1,attacks:[24,46,47,48],height:75,reward:0,pattern:0},
        {name:'Duckit',alt:'',life:18,speed:6,damage:1,attacks:[25,12,13/*,14*/],height:60,reward:0,pattern:0},
        {name:'Human',alt:'',life:10,speed:10,damage:1,attacks:[1],height:75,reward:10,pattern:0},
        {name:'Fat Human',alt:'',life:25,speed:15,damage:1,attacks:[5],height:66,reward:15,pattern:0},//10
        {name:'Long Human',alt:'',life:15,speed:8,damage:1,attacks:[4],height:84,reward:15,pattern:0},
        {name:'Big Human',alt:'',life:30,speed:12,damage:2,attacks:[2,7],height:90,reward:20,pattern:0},
        {name:'Management Soldier',alt:'',life:240,speed:9,damage:2,attacks:[],height:78,reward:80,pattern:0},
        {name:'Management Officer',alt:'',life:150,speed:9,damage:2,attacks:[],height:78,reward:160,pattern:0},
        {name:'Duck',alt:'',life:12,speed:6,damage:1,attacks:[39],height:60,reward:5,pattern:0},
        {name:'Desert Control',alt:'Soldier',life:120,speed:9,damage:2,attacks:[],height:78,reward:20,pattern:0},
        {name:'Desert Control',alt:'Officer',life:75,speed:9,damage:2,attacks:[],height:78,reward:40,pattern:0},
        {name:'Bounce',alt:'',life:10,speed:7,damage:1,attacks:[1,53],height:75,reward:10,pattern:0},
        {name:'Fat Bounce',alt:'',life:25,speed:11,damage:1,attacks:[5,53],height:66,reward:15,pattern:0},
        {name:'Long Bounce',alt:'',life:15,speed:6,damage:1,attacks:[4,53],height:84,reward:15,pattern:0},//20
        {name:'Big Bounce',alt:'',life:30,speed:9,damage:2,attacks:[2,7,53],height:90,reward:20,pattern:0},
        {name:'Scrapper',alt:'',life:16,speed:10,damage:1,attacks:[1,56],height:75,reward:10,pattern:0},
        {name:'Fat Scrapper',alt:'',life:40,speed:15,damage:1,attacks:[5,56],height:66,reward:15,pattern:0},
        {name:'Long Scrapper',alt:'',life:24,speed:8,damage:1,attacks:[4,56],height:84,reward:15,pattern:0},
        {name:'Big Scrapper',alt:'',life:48,speed:12,damage:2,attacks:[2,7,56],height:90,reward:20,pattern:0},
        {name:'Builder',alt:'',life:20,speed:10,damage:1,attacks:[1,55],height:75,reward:10,pattern:0},
        {name:'Fat Builder',alt:'',life:50,speed:15,damage:1,attacks:[5,55],height:66,reward:15,pattern:0},
        {name:'Long Builder',alt:'',life:30,speed:8,damage:1,attacks:[4,55],height:84,reward:15,pattern:0},
        {name:'Big Builder',alt:'',life:60,speed:12,damage:2,attacks:[2,7,55],height:90,reward:20,pattern:0},
        {name:'Red',alt:'',life:18,speed:10,damage:1,attacks:[1,59],height:75,reward:10,pattern:0},//30
        {name:'Fat Red',alt:'',life:45,speed:15,damage:1,attacks:[5,59],height:66,reward:15,pattern:0},
        {name:'Long Red',alt:'',life:27,speed:8,damage:1,attacks:[4,59],height:84,reward:15,pattern:0},
        {name:'Big Red',alt:'',life:54,speed:12,damage:2,attacks:[2,7,59],height:90,reward:20,pattern:0},
        {name:'Reichswehr',alt:'',life:14,speed:10,damage:2,attacks:[1,60],height:75,reward:10,pattern:0},
        {name:'Fat Reichswehr',alt:'',life:35,speed:15,damage:2,attacks:[5,60],height:66,reward:15,pattern:0},
        {name:'Long Reichswehr',alt:'',life:21,speed:8,damage:2,attacks:[4,60],height:84,reward:15,pattern:0},
        {name:'Big Reichswehr',alt:'',life:42,speed:12,damage:3,attacks:[2,7,60],height:90,reward:20,pattern:0},
        {name:'Nerfer',alt:'',life:12,speed:10,damage:1,attacks:[1,2,3],height:75,reward:10,pattern:0},
        {name:'Buffer',alt:'',life:12,speed:10,damage:1,attacks:[24,25,26],height:75,reward:10,pattern:0},
        {name:'Big Nerfer',alt:'',life:36,speed:12,damage:2,attacks:[1,2,3],height:90,reward:20,pattern:0},//40
        {name:'Big Buffer',alt:'',life:36,speed:12,damage:2,attacks:[24,25,26],height:90,reward:20,pattern:0},
        {name:'Thug',alt:'',life:20,speed:20,damage:1,attacks:[1,61],height:75,reward:10,pattern:0},
        {name:'Fat Thug',alt:'',life:50,speed:30,damage:1,attacks:[5,61],height:66,reward:15,pattern:0},
        {name:'Long Thug',alt:'',life:30,speed:16,damage:1,attacks:[4,61],height:84,reward:15,pattern:0},
        {name:'Big Thug',alt:'',life:60,speed:24,damage:2,attacks:[2,7,61],height:90,reward:20,pattern:0},
        {name:'Management Robot',alt:'',life:60,speed:9,damage:2,attacks:[62],height:78,reward:80,pattern:0},
        {name:'Quack Bridgade',alt:'',life:18,speed:5,damage:1,attacks:[39,63],height:60,reward:10,pattern:0},
        {name:'Agent Duck',alt:'',life:30,speed:7,damage:1,attacks:[],height:60,reward:15,pattern:0},
        {name:'Shark',alt:'',life:12,speed:8,damage:1,attacks:[1,67],height:75,reward:10,pattern:0},
        {name:'Fat Shark',alt:'',life:30,speed:12,damage:1,attacks:[5,67],height:66,reward:15,pattern:0},//50
        {name:'Long Shark',alt:'',life:18,speed:6,damage:1,attacks:[4,67],height:84,reward:15,pattern:0},
        {name:'Big Shark',alt:'',life:36,speed:10,damage:2,attacks:[2,7,67],height:90,reward:20,pattern:0},
        {name:'Cartel',alt:'',life:24,speed:10,damage:1,attacks:[1,68],height:75,reward:10,pattern:0},
        {name:'Fat Cartel',alt:'',life:60,speed:15,damage:1,attacks:[5,68],height:66,reward:15,pattern:0},
        {name:'Long Cartel',alt:'',life:36,speed:8,damage:1,attacks:[4,68],height:84,reward:15,pattern:0},
        {name:'Big Cartel',alt:'',life:72,speed:12,damage:2,attacks:[2,7,68],height:90,reward:20,pattern:0},
        {name:'Junkie',alt:'',life:10,speed:10,damage:1,attacks:[1,69],height:75,reward:10,pattern:0},
        {name:'Fat Junkie',alt:'',life:25,speed:15,damage:1,attacks:[5,69],height:66,reward:15,pattern:0},
        {name:'Long Junkie',alt:'',life:15,speed:8,damage:1,attacks:[4,69],height:84,reward:15,pattern:0},
        {name:'Big Junkie',alt:'',life:30,speed:12,damage:2,attacks:[2,7,69],height:90,reward:20,pattern:0},//60
        {name:'Management',alt:'Special Forces',life:360,speed:9,damage:3,attacks:[],height:78,reward:120,pattern:0},
        {name:'Duck Force',alt:'',life:24,speed:9,damage:1,attacks:[39,70],height:60,reward:10,pattern:0},
        {name:'Funny Man',alt:'',life:10,speed:9,damage:1,attacks:[1,71,72,73,74],height:75,reward:10,pattern:0},
        {name:'Fat Funny Man',alt:'',life:25,speed:13,damage:1,attacks:[5,71,72,73,74],height:66,reward:15,pattern:0},
        {name:'Long Funny Man',alt:'',life:15,speed:7,damage:1,attacks:[4,71,72,73,74],height:84,reward:15,pattern:0},
        {name:'Big Funny Man',alt:'',life:30,speed:11,damage:2,attacks:[2,7,71,72,73,74],height:90,reward:20,pattern:0},
        {name:'Chonk',alt:'',life:90,speed:20,damage:3,attacks:[75,7],height:120,reward:100,pattern:1},
        {name:'Great Duckus',alt:'',life:72,speed:12,damage:2,attacks:[77,39],height:90,reward:50,pattern:1},
        {name:'Lord Bounce',alt:'',life:150,speed:15,damage:3,attacks:[79,53],height:96,reward:100,pattern:1},
        {name:'Scrap King',alt:'',life:80,speed:18,damage:3,attacks:[56],height:90,reward:100,pattern:0},//70
        {name:'Armored Builder',alt:'',life:180,speed:14,damage:4,attacks:[1,55],height:75,reward:100,pattern:0},
        {name:'Comrade',alt:'',life:288,speed:13,damage:3,attacks:[83,59,84],height:75,reward:100,pattern:1},
        {name:'Militarian',alt:'',life:350,speed:13,damage:4,attacks:[91,60],height:90,reward:100,pattern:1},
        {name:'Nerfmaster',alt:'',life:96,speed:12,damage:2,attacks:[85,86,87],height:75,reward:50,pattern:0},
        {name:'Buffmaster',alt:'',life:96,speed:12,damage:2,attacks:[88,89,90],height:75,reward:50,pattern:0},
        {name:'Welder',alt:'',life:480,speed:28,damage:3,attacks:[30],height:90,reward:100,pattern:0},
        {name:'Big Duck',alt:'',life:30,speed:7,damage:1,attacks:[39,93],height:75,reward:10,pattern:0},
        {name:'Big Quack Bridgade',alt:'',life:45,speed:6,damage:1,attacks:[39,63,93],height:75,reward:20,pattern:0},
        {name:'Elite Agent Duck',alt:'',life:60,speed:7,damage:2,attacks:[],height:60,reward:30,pattern:0},
        {name:'Master Quack',alt:'',life:162,speed:10,damage:3,attacks:[96,39,63],height:75,reward:100,pattern:1},//80
        {name:'Duck 006',alt:'',life:240,speed:13,damage:4,attacks:[93],height:75,reward:100,pattern:0},
        {name:'MoneyMaster',alt:'',life:384,speed:12,damage:3,attacks:[1,101],height:90,reward:100,pattern:0},
        {name:'Roger Reviv',alt:'',life:600,speed:22,damage:4,attacks:[102,68],height:75,reward:100,pattern:1},
        {name:'Cook',alt:'',life:360,speed:12,damage:2,attacks:[99,7,100],height:90,reward:100,pattern:1},
        {name:'Big Duck Force',alt:'',life:60,speed:10,damage:1,attacks:[39,93],height:75,reward:20,pattern:0},
        {name:'General Duckion',alt:'',life:400,speed:12,damage:4,attacks:[103,39,70],height:75,reward:100,pattern:1},
        {name:'Joking Jimmy',alt:'',life:150,speed:11,damage:1,attacks:[104],height:66,reward:100,pattern:0},
        {name:'Director Illyesc',alt:'',life:900,speed:18,damage:2,attacks:[105,106,107],height:78,reward:10000,pattern:1},
        {name:'Bulwark',alt:'',life:30,speed:15,damage:1,attacks:[1,109],height:75,reward:10,pattern:0},
        {name:'Fat Bulwark',alt:'',life:75,speed:23,damage:1,attacks:[5,109],height:66,reward:15,pattern:0},//90
        {name:'Long Bulwark',alt:'',life:45,speed:12,damage:1,attacks:[4,109],height:84,reward:15,pattern:0},
        {name:'Big Bulwark',alt:'',life:90,speed:18,damage:2,attacks:[2,7,109],height:90,reward:20,pattern:0},
        {name:'Wiper',alt:'',life:26,speed:11,damage:1,attacks:[1,110],height:75,reward:10,pattern:0},
        {name:'Fat Wiper',alt:'',life:65,speed:17,damage:1,attacks:[5,110],height:66,reward:15,pattern:0},
        {name:'Long Wiper',alt:'',life:39,speed:9,damage:1,attacks:[4,110],height:84,reward:15,pattern:0},
        {name:'Big Wiper',alt:'',life:78,speed:13,damage:2,attacks:[2,7,110],height:90,reward:20,pattern:0},
        {name:'Wiper Boss',alt:'',life:1,speed:0,damage:0,attacks:[],height:75,reward:0,pattern:0},
        {name:'Wiper Messenger',alt:'',life:1,speed:0,damage:0,attacks:[],height:75,reward:0,pattern:0},
        {name:'Sakura',alt:'',life:300,speed:8,damage:3,attacks:[124,125,126,133],height:72,reward:0,pattern:1},
        {name:'Hider',alt:'',life:1,speed:0,damage:0,attacks:[],height:75,reward:0,pattern:0},//100
        {name:'Fat Hider',alt:'',life:1,speed:0,damage:0,attacks:[],height:66,reward:0,pattern:0},
        {name:'Long Hider',alt:'',life:1,speed:0,damage:0,attacks:[],height:84,reward:0,pattern:0},
        {name:'Big Hider',alt:'',life:1,speed:0,damage:0,attacks:[],height:90,reward:0,pattern:0},
        {name:'Hider Boss',alt:'',life:1,speed:0,damage:0,attacks:[],height:120,reward:0,pattern:0},
        {name:'The Commandant',alt:'',life:375,speed:15,damage:3,attacks:[111],height:78,reward:100,pattern:1},
        {name:'Bomber',alt:'',life:25,speed:10,damage:1,attacks:[1],height:75,reward:10,pattern:0},
        {name:'Fat Bomber',alt:'',life:63,speed:15,damage:1,attacks:[5],height:66,reward:15,pattern:0},
        {name:'Long Bomber',alt:'',life:38,speed:8,damage:1,attacks:[4],height:84,reward:15,pattern:0},
        {name:'Big Bomber',alt:'',life:75,speed:12,damage:2,attacks:[2,7],height:90,reward:20,pattern:0},
        {name:'The Deflagrator',alt:'',life:750,speed:14,damage:2,attacks:[113,114],height:90,reward:100,pattern:1},//110
        {name:'Shielder',alt:'',life:32,speed:10,damage:0.5,attacks:[1,116],height:75,reward:10,pattern:0},
        {name:'Fat Shielder',alt:'',life:80,speed:15,damage:0.5,attacks:[5,116],height:66,reward:15,pattern:0},
        {name:'Long Shielder',alt:'',life:48,speed:8,damage:0.5,attacks:[4,116],height:84,reward:15,pattern:0},
        {name:'Big Shielder',alt:'',life:96,speed:12,damage:1,attacks:[2,7,116],height:90,reward:20,pattern:0},
        {name:'Superior Protector',alt:'',life:160,speed:14,damage:1,attacks:[117,116],height:90,reward:100,pattern:1},
        {name:'Gent',alt:'',life:20,speed:8,damage:1,attacks:[1,123],height:75,reward:10,pattern:0},
        {name:'Fat Gent',alt:'',life:50,speed:12,damage:1,attacks:[5,123],height:66,reward:15,pattern:0},
        {name:'Long Gent',alt:'',life:30,speed:6,damage:1,attacks:[4,123],height:84,reward:15,pattern:0},
        {name:'Big Gent',alt:'',life:60,speed:10,damage:2,attacks:[2,7,123],height:90,reward:20,pattern:0},
        {name:'The Goodman',alt:'',life:200,speed:10,damage:3,attacks:[123],height:75,reward:100,pattern:0},
    ],weapon:[
        {name:'Unarmed',damage:2,attacks:[0],cost:0},//0
        {name:'Stick',damage:4,attacks:[8],cost:25},
        {name:'Pistol',damage:4,attacks:[8,9],cost:200},
        {name:'Lighter',damage:1,attacks:[8,10],cost:100},
        {name:'Taser',damage:1,attacks:[8,11],cost:150},
        {name:'Shotgun',damage:6,attacks:[8,15],cost:500},
        {name:'Sniper',damage:5,attacks:[8,9,16],cost:400},
        {name:'Metal Beam',damage:8,attacks:[8,17],cost:300},
        {name:'Submachine',damage:4,attacks:[8,18],cost:600},
        {name:'Management CR-12',damage:4,attacks:[19],cost:5000},
        {name:'Management HVM-5',damage:8,attacks:[20],cost:5000},//10
        {name:'Management FBP-34',damage:10,attacks:[21],cost:5000},
        {name:'Bandaid',damage:1,attacks:[8,22],cost:50},
        {name:'Baseball Bat',damage:6,attacks:[8,23],cost:200},
        {name:'Time Bomb',damage:5,attacks:[8,49],cost:450},
        {name:'Knife',damage:7,attacks:[50,51],cost:250},
        {name:'Medpack',damage:2,attacks:[8,22,52],cost:100},
        {name:'Electrobaton',damage:12,attacks:[8,54],cost:2500},
        {name:'Small Hammer',damage:5,attacks:[8,17,57],cost:175},
        {name:'Sickle',damage:5,attacks:[50,58],cost:175},
        {name:'Karate',damage:4,attacks:[64,65,66],cost:150},//20
        {name:'Metal Frame',damage:10,attacks:[8,17,76],cost:450},
        {name:'Duckus Bat',damage:6,attacks:[8,23,78],cost:225},
        {name:'Pole',damage:5,attacks:[8,80],cost:175},
        {name:'Big Gun',damage:8,attacks:[8,9,81],cost:425},
        {name:'Large Hammer',damage:5,attacks:[17,57,82],cost:200},
        {name:'Hammer&Sickle',damage:7.5,attacks:[8,17,50,57,58],cost:350},
        {name:'Welding Tools',damage:8,attacks:[8,92],cost:400},
        {name:'Elite Karate',damage:4,attacks:[64,65,66,94,95],cost:250},
        {name:'Expert Karate',damage:4,attacks:[64,65,66,94,95,97,98],cost:325},
        {name:'Management FBP-35N',damage:10,attacks:[108],cost:10000},//30
        {name:'Towhook',damage:4,attacks:[127,128,129,130,134],cost:33550336},
        {name:'Fire Bomb',damage:3,attacks:[8,112],cost:475},
        {name:'Bomb Pack',damage:3,attacks:[8,49,112],cost:700},
        {name:'Sharp Stick',damage:4,attacks:[8,115],cost:50},
        {name:'Pipe',damage:5,attacks:[8,17],cost:150},
        {name:'Massive Gun',damage:8,attacks:[8,9,118],cost:500},
        {name:'Sawblade',damage:2,attacks:[119,120],cost:250},
        {name:'Pencil',damage:2,attacks:[8,115],cost:25},
        {name:'Shield',damage:5,attacks:[8,121,122],cost:125},
        {name:'Towhook',damage:2,attacks:[131,132],cost:33550336},//40
        {name:'Twig',damage:3,attacks:[8],cost:10},
        {name:'Large Medpack',damage:4,attacks:[8,22,52],cost:250},
        {name:'Clustergun',damage:4,attacks:[8,15],cost:325},
        {name:'Sword',damage:9,attacks:[50,51],cost:350},
    ],attack:[
        {name:'Punch'                   ,damage:1   ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Basic attack'},//0
        {name:'Nerf Damage'             ,damage:0   ,target:0,class:1,uses:0 ,accuracy:1   ,description:'Decreases enemy damage'},
        {name:'Nerf Defense'            ,damage:0   ,target:0,class:1,uses:0 ,accuracy:1   ,description:'Decreases enemy defense'},
        {name:'Nerf Speed'              ,damage:0   ,target:0,class:1,uses:0 ,accuracy:1   ,description:'Decreases enemy speed'},
        {name:'Buff Damage'             ,damage:0   ,target:1,class:1,uses:0 ,accuracy:1   ,description:'Increases self damage'},
        {name:'Buff Defense'            ,damage:0   ,target:1,class:1,uses:0 ,accuracy:1   ,description:'Increases self defense'},
        {name:'Buff Speed'              ,damage:0   ,target:1,class:1,uses:0 ,accuracy:1   ,description:'Increases self speed'},
        {name:'Shockwave'               ,damage:0.5 ,target:2,class:0,uses:0 ,accuracy:1   ,description:'Damages all enemies'},
        {name:'Whack'                   ,damage:1   ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Hit enemy with object'},
        {name:'Shoot'                   ,damage:2   ,target:0,class:2,uses:10,accuracy:0.9 ,description:'Fire weapon'},
        {name:'Ignite'                  ,damage:1   ,target:0,class:3,uses:20,accuracy:1   ,description:'Sets enemy on fire'},//10
        {name:'Stun'                    ,damage:1   ,target:0,class:3,uses:5 ,accuracy:1   ,description:'Stuns enemy'},
        {name:'Slap'                    ,damage:3   ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Slap twice'},
        {name:'Slap Parade'             ,damage:2   ,target:2,class:0,uses:20,accuracy:1   ,description:'Slap all enemies'},
        {name:'Thunder Slap'            ,damage:4   ,target:0,class:0,uses:10,accuracy:1   ,description:'Slap and confuse'},
        {name:'Area Shot'               ,damage:2   ,target:0,class:2,uses:5 ,accuracy:0.8 ,description:'Sprays bullets widely'},
        {name:'Snipe'                   ,damage:3   ,target:0,class:2,uses:5 ,accuracy:1   ,description:'Ignores defense'},
        {name:'Smash'                   ,damage:1.5 ,target:0,class:0,uses:5 ,accuracy:0.9 ,description:'Hits hard'},
        {name:'Sustain Fire'            ,damage:2   ,target:0,class:2,uses:5 ,accuracy:0.8 ,description:'Fire multiple shots'},
        {name:'Overwhelming Force'      ,damage:1   ,target:0,class:2,uses:20,accuracy:0.5 ,description:'Fire swarm of shots'},
        {name:'Concentrated Elimination',damage:2.5 ,target:0,class:2,uses:50,accuracy:1   ,description:'Good aiming'},//20
        {name:'Perfected Strike'        ,damage:3.5 ,target:0,class:2,uses:10,accuracy:1   ,description:'Hit the best spot'},
        {name:'Heal'                    ,damage:5   ,target:3,class:0,uses:10,accuracy:1   ,description:'Help out'},
        {name:'Bonk'                    ,damage:1   ,target:0,class:0,uses:20,accuracy:1   ,description:'Knock them together'},
        {name:'Ally Buff Damage'        ,damage:0   ,target:3,class:1,uses:0 ,accuracy:1   ,description:'Increase ally damage'},
        {name:'Ally Buff Defense'       ,damage:0   ,target:3,class:1,uses:0 ,accuracy:1   ,description:'Increase ally defense'},
        {name:'Ally Buff Speed'         ,damage:0   ,target:3,class:1,uses:0 ,accuracy:1   ,description:'Increase ally speed'},
        {name:'Lunch'                   ,damage:2   ,target:4,class:1,uses:20,accuracy:1   ,description:'Share some food'},
        {name:'Protection'              ,damage:1   ,target:3,class:1,uses:5 ,accuracy:1   ,description:'Keep ally alive'},
        {name:'Cheap Shot'              ,damage:3   ,target:0,class:2,uses:5 ,accuracy:0.8 ,description:"Fire before they're ready"},
        {name:'Charge'                  ,damage:7   ,target:5,class:0,uses:10,accuracy:1   ,description:'Charge the front'},//30
        {name:'Enlarge'                 ,damage:0   ,target:1,class:1,uses:10,accuracy:1   ,description:'Power yourself up'},
        {name:'Mixup'                   ,damage:5   ,target:2,class:0,uses:5 ,accuracy:1   ,description:'Break their formation'},
        {name:'Verbal Assault'          ,damage:4   ,target:0,class:0,uses:20,accuracy:0.8 ,description:'Emotional damage'},
        {name:'Supply'                  ,damage:2   ,target:3,class:1,uses:5 ,accuracy:1   ,description:'Refill ally'},
        {name:'Invigorate'              ,damage:4   ,target:3,class:3,uses:5 ,accuracy:1   ,description:'Power up ally'},
        {name:'Bore'                    ,damage:2   ,target:0,class:3,uses:10,accuracy:1   ,description:'Waste time'},
        {name:"You're Fired"            ,damage:10  ,target:0,class:3,uses:5 ,accuracy:0.6 ,description:'Downsize'},
        {name:"Financial Crime"         ,damage:4   ,target:0,class:3,uses:5 ,accuracy:1   ,description:'Extort money'},
        {name:'Quack'                   ,damage:1   ,target:0,class:0,uses:0 ,accuracy:0.6 ,description:'Loud noise'},
        {name:'Slam'                    ,damage:9   ,target:0,class:0,uses:10,accuracy:0.8 ,description:'Fall on enemy'},//40
        {name:'Cleanup'                 ,damage:0   ,target:4,class:3,uses:5 ,accuracy:1   ,description:'Remove team stat changes'},
        {name:'1v1'                     ,damage:4   ,target:0,class:0,uses:20,accuracy:1   ,description:'Fight me'},
        {name:'Drinks'                  ,damage:1   ,target:4,class:1,uses:10,accuracy:1   ,description:'Share the supply'},
        {name:'Oil Up'                  ,damage:6   ,target:0,class:1,uses:20,accuracy:1   ,description:'Flammable material'},
        {name:'Pass Out'                ,damage:2   ,target:1,class:1,uses:0 ,accuracy:1   ,description:'Fall asleep'},
        {name:'Flash Powder'            ,damage:1   ,target:2,class:1,uses:10,accuracy:1   ,description:'Throw strange powder'},
        {name:'Particles'               ,damage:6   ,target:2,class:0,uses:5 ,accuracy:1   ,description:'Fire storm of particles'},
        {name:'Spray'                   ,damage:3   ,target:2,class:2,uses:20,accuracy:0.1 ,description:'Ready, fire, aim'},
        {name:'Rig Bomb'                ,damage:4   ,target:0,class:4,uses:10,accuracy:1   ,description:'Leave a bomb'},
        {name:'Stab'                    ,damage:1   ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Stab the enemy'},//50
        {name:'Fast Stab'               ,damage:1   ,target:0,class:0,uses:10,accuracy:1   ,description:'Cause bleeding'},
        {name:'Status Heal'             ,damage:0   ,target:3,class:0,uses:10,accuracy:1   ,description:'Clear statuses'},
        {name:'Quick Strike'            ,damage:1   ,target:0,class:0,uses:0 ,accuracy:0.5 ,description:'Hit in rapid fashion'},
        {name:'Electrowhack'            ,damage:1   ,target:0,class:0,uses:5 ,accuracy:1   ,description:'Hit and stun'},
        {name:'Repair'                  ,damage:4   ,target:3,class:0,uses:10,accuracy:1   ,description:'Fix up'},
        {name:'Divide'                  ,damage:1   ,target:0,class:0,uses:0 ,accuracy:0.8 ,description:'Take apart'},
        {name:'Pound'                   ,damage:1   ,target:0,class:0,uses:5 ,accuracy:1   ,description:'Hit in the head'},
        {name:'Cut Down'                ,damage:0.5 ,target:6,class:0,uses:10,accuracy:1   ,description:'Cut through them'},
        {name:'Share the Wealth'        ,damage:4   ,target:4,class:0,uses:0 ,accuracy:1   ,description:'Share the heals'},
        {name:'Blitz'                   ,damage:3   ,target:0,class:2,uses:5 ,accuracy:0.6 ,description:'Fire quickly'},//60
        {name:'Shove'                   ,damage:1   ,target:0,class:0,uses:0 ,accuracy:0.8 ,description:'Push into each other'},
        {name:'Mechanize'               ,damage:10  ,target:1,class:1,uses:5 ,accuracy:1   ,description:'Self-repair'},
        {name:'Hyperquack'              ,damage:1   ,target:0,class:0,uses:5 ,accuracy:0.4 ,description:'Loud noise'},
        {name:'Combo Punch'             ,damage:1.25,target:0,class:0,uses:0 ,accuracy:1   ,description:'Punch and build combo'},
        {name:'Combo Bonk'              ,damage:1   ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Bonk and build combo'},
        {name:'Combo Finish'            ,damage:1   ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Hit and expend combo'},
        {name:'Steal'                   ,damage:1   ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Take cash'},
        {name:'Slash'                   ,damage:3   ,target:0,class:0,uses:0 ,accuracy:0.9 ,description:'Major bleed'},
        {name:'Get High'                ,damage:3   ,target:1,class:1,uses:1 ,accuracy:1   ,description:'Take the good stuff'},
        {name:'Entrench'                ,damage:2   ,target:1,class:1,uses:5 ,accuracy:1   ,description:'Armor yourself heavily'},//70
        {name:'Verbal Burn'             ,damage:2   ,target:0,class:2,uses:1 ,accuracy:0.4 ,description:'Burn him up'},
        {name:'Verbal Confusion'        ,damage:5   ,target:0,class:2,uses:1 ,accuracy:0.6 ,description:'Extreme confusion'},
        {name:'Emotional Reduction'     ,damage:5   ,target:0,class:2,uses:1 ,accuracy:0.6 ,description:'Emotional suffering'},
        {name:'Waste Time'              ,damage:1   ,target:0,class:2,uses:1 ,accuracy:1   ,description:'Get bored'},
        {name:'Chonk Up'                ,damage:1   ,target:1,class:1,uses:1 ,accuracy:1   ,description:'Prepare for pain'},
        {name:'Wide Smash'              ,damage:3   ,target:0,class:0,uses:0 ,accuracy:0.4 ,description:'Inaccurate heavy smash'},
        {name:'Motivational Quack'      ,damage:0.5 ,target:4,class:0,uses:0 ,accuracy:1   ,description:'Quack for allies'},
        {name:'Double Bonk'             ,damage:1   ,target:0,class:0,uses:5 ,accuracy:1   ,description:'Knock three together'},
        {name:'Quick Sweep'             ,damage:1   ,target:0,class:0,uses:0 ,accuracy:0.5 ,description:'Sweep in rapid fashion'},
        {name:'Defensive Hold'          ,damage:1   ,target:1,class:1,uses:10,accuracy:1   ,description:'Defend yourself'},//80
        {name:'Heavy Shot'              ,damage:3   ,target:0,class:2,uses:5 ,accuracy:0.75,description:'Very big gun'},
        {name:'Pound Bonk'              ,damage:1   ,target:0,class:0,uses:5 ,accuracy:1   ,description:'Hit in the head and bonk'},
        {name:'No Step Back'            ,damage:1   ,target:4,class:1,uses:1 ,accuracy:1   ,description:'No retreat'},
        {name:'Encircling Tactics'      ,damage:1   ,target:7,class:0,uses:10,accuracy:1   ,description:'Bring in backup'},
        {name:'Heavy Nerf Damage'       ,damage:0   ,target:0,class:1,uses:0 ,accuracy:1   ,description:'Greatly decreases enemy damage'},
        {name:'Heavy Nerf Defense'      ,damage:0   ,target:0,class:1,uses:0 ,accuracy:1   ,description:'Greatly decreases enemy defense'},
        {name:'Heavy Nerf Speed'        ,damage:0   ,target:0,class:1,uses:0 ,accuracy:1   ,description:'Greatly decreases enemy speed'},
        {name:'Heavy Buff Damage'       ,damage:0   ,target:3,class:1,uses:0 ,accuracy:1   ,description:'Greatly increase ally damage'},
        {name:'Heavy Buff Defense'      ,damage:0   ,target:3,class:1,uses:0 ,accuracy:1   ,description:'Greatly increase ally defense'},
        {name:'Heavy Buff Speed'        ,damage:0   ,target:3,class:1,uses:0 ,accuracy:1   ,description:'Greatly increase ally speed'},//90
        {name:'First Strike'            ,damage:0.5 ,target:2,class:2,uses:1 ,accuracy:1   ,description:'Destroy quickly'},
        {name:'Weld'                    ,damage:1   ,target:0,class:0,uses:0 ,accuracy:0.8 ,description:'Burn up'},
        {name:'Get Shredded'            ,damage:1   ,target:0,class:0,uses:0 ,accuracy:0.8 ,description:'Demonstrate your power'},
        {name:'Combo Flurry'            ,damage:0.5 ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Build lots of combo'},
        {name:'Combo Disable'           ,damage:0.75,target:0,class:0,uses:0 ,accuracy:1   ,description:'Stun and build combo'},
        {name:'Quack of Supremacy'      ,damage:0.5 ,target:2,class:1,uses:1 ,accuracy:1   ,description:'Quack and destroy'},
        {name:'Combo Destruction'       ,damage:2   ,target:0,class:0,uses:10,accuracy:1   ,description:'Do massive damage and build combo'},
        {name:'Flaming Combo Finish'    ,damage:1   ,target:0,class:0,uses:10,accuracy:1   ,description:'Hit and expend combo'},
        {name:'Permanent High'          ,damage:100 ,target:1,class:1,uses:1 ,accuracy:1   ,description:'Take the good stuff'},
        {name:'Dust Storm'              ,damage:1   ,target:2,class:0,uses:5 ,accuracy:1   ,description:'Attack with strange dust'},//100
        {name:'Cash Out'                ,damage:1   ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Take lots of cash'},
        {name:'Airstrike'               ,damage:5   ,target:2,class:2,uses:1 ,accuracy:1   ,description:'Attack from the skies'},
        {name:'Crack Shot'              ,damage:12  ,target:0,class:2,uses:1 ,accuracy:1   ,description:'Fire a powerful blow'},
        {name:'Verbal Destruction'      ,damage:1   ,target:0,class:2,uses:0 ,accuracy:0.6 ,description:'Annihlate him with words'},
        {name:'Monologue'               ,damage:0   ,target:2,class:1,uses:1 ,accuracy:1   ,description:'Discuss the future'},
        {name:'Arrogance'               ,damage:1   ,target:1,class:0,uses:10,accuracy:1   ,description:'Laugh in your power'},
        {name:'Assured Destruction'     ,damage:1   ,target:4,class:0,uses:10,accuracy:1   ,description:'Motivate allies'},
        {name:'Supreme Firepower'       ,damage:4   ,target:0,class:2,uses:50,accuracy:1   ,description:'Utter destruction via firepower'},
        {name:'Ally armor'              ,damage:2   ,target:3,class:1,uses:5 ,accuracy:1   ,description:'Protect ally defensively'},
        {name:'Wipe'                    ,damage:0   ,target:2,class:3,uses:1 ,accuracy:1   ,description:'Remove enemy status changes'},//110
        {name:'Deprecation'             ,damage:0.25,target:4,class:1,uses:1 ,accuracy:1   ,description:'Growing weakness'},
        {name:'Rig Fire Bomb'           ,damage:4   ,target:0,class:4,uses:10,accuracy:1   ,description:'Leave a fire bomb'},
        {name:'Flame Run'               ,damage:0   ,target:2,class:3,uses:1 ,accuracy:1   ,description:'Begin the burning'},
        {name:'Shotgun Sidearm'         ,damage:10  ,target:0,class:2,uses:5 ,accuracy:0.8 ,description:'Sprays wide fire'},
        {name:'Poke'                    ,damage:0.5 ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Cause a little bleed'},
        {name:'Absorb'                  ,damage:0   ,target:1,class:0,uses:1 ,accuracy:1   ,description:'Get through attacks'},
        {name:'Multiabsorb'             ,damage:0   ,target:1,class:0,uses:1 ,accuracy:1   ,description:'Get team through attacks'},
        {name:'Heavy Shot'              ,damage:2.5 ,target:0,class:2,uses:5 ,accuracy:0.8 ,description:'Fire a large shot'},
        {name:'Saw'                     ,damage:1   ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Multiple small hits'},
        {name:'Deep Saw'                ,damage:1   ,target:0,class:0,uses:10,accuracy:1   ,description:'Causes additional bleed'},//120
        {name:'Small Block'             ,damage:1   ,target:1,class:1,uses:20,accuracy:1   ,description:'Reduce next hits'},
        {name:'Reflect'                 ,damage:0   ,target:0,class:0,uses:5 ,accuracy:1   ,description:'Reverse next attack'},
        {name:'Copy'                    ,damage:0   ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Steal enemy attack'},
        {name:'Flash'                   ,damage:0   ,target:2,class:1,uses:1 ,accuracy:1   ,description:"I'm not writing this!"},
        {name:'Calm'                    ,damage:1   ,target:0,class:0,uses:0 ,accuracy:1   ,description:'The remaining peace'},
        {name:'Petal Dance'             ,damage:2   ,target:2,class:1,uses:10,accuracy:1   ,description:'Throw several petals'},
        {name:'Windslash'               ,damage:0.5 ,target:2,class:0,uses:10,accuracy:1   ,description:'Rush through enemies'},
        {name:'Decisive Stab'           ,damage:1.5 ,target:0,class:0,uses:10,accuracy:1   ,description:'Cause damage and bleeding'},
        {name:'Parry'                   ,damage:0   ,target:0,class:0,uses:5 ,accuracy:1   ,description:'Reverse next attack'},
        {name:'Throw'                   ,damage:4   ,target:0,class:2,uses:0 ,accuracy:1   ,description:'Throw weapon'},//130
        {name:'Collect'                 ,damage:0   ,target:2,class:0,uses:0 ,accuracy:1   ,description:'Pick up weapon'},
        {name:'Rough Combat'            ,damage:0.25,target:0,class:0,uses:0 ,accuracy:1   ,description:'Beat up and get beat up'},
        {name:'Silence'                 ,damage:0   ,target:0,class:0,uses:0 ,accuracy:1   ,description:'Cancels abilities'},
        {name:'Impale'                  ,damage:1   ,target:0,class:5,uses:0 ,accuracy:1   ,description:'Stab and disable'},
    ]
}
stage={scene:'walk',scale:1}
graphics={main:0,backgrounds:[],minor:[]}
transition={trigger:false,anim:0,scene:stage.scene}
inputs={mouse:{x:0,y:0},rel:{x:0,y:0},keys:[[false,false,false,false],[false,false,false,false]]}
entities={particles:[]}
run={fore:[]}
dev={id:false,auto:false}
combatants=[
    {id:/*1*/5,weapon:/*3*/6,team:0},
    {id:2,weapon:1,team:0},
    {id:3,weapon:12,team:0},
    {id:6,weapon:38,team:0},
    {id:0,weapon:0,team:1},
    {id:0,weapon:0,team:1},
    {id:0,weapon:0,team:1},
    {id:0,weapon:0,team:1},
]
a=0;b=0;c=0;d=0;e=0;f=0;g=0;h=0;i=0;j=0;k=0;l=0;m=0;n=0;o=0;p=0
la=0;lb=0;lc=0;ld=0;le=0;lf=0;lg=0;lh=0;li=0;lj=0;lk=0;ll=0;lm=0;ln=0;lo=0;lp=0